### ISSUE TITLE
NameError with Active Support 4.2

### ISSUE THREAD

**Issue by jonahb** [jayfajardo/openlibrary#20]
With Active Support 4.2 (Ruby 2.1), `require 'openlibrary'` produces a NameError:

````
NameError: uninitialized constant ActiveSupport::Deprecation
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/core_ext/module/deprecation.rb:21:in `deprecate'
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/core_ext/class/delegating_attributes.rb:26:in `<class:Class>'
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/core_ext/class/delegating_attributes.rb:6:in `<top (required)>'
	from /opt/local/lib/ruby2.1/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /opt/local/lib/ruby2.1/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/core_ext/class.rb:2:in `<top (required)>'
	from /opt/local/lib/ruby2.1/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /opt/local/lib/ruby2.1/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/core_ext.rb:1:in `each'
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/core_ext.rb:1:in `<top (required)>'
	from /opt/local/lib/ruby2.1/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /opt/local/lib/ruby2.1/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/openlibrary-2.1.3/lib/openlibrary/request.rb:2:in `<top (required)>'
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/openlibrary-2.1.3/lib/openlibrary/client.rb:1:in `require_relative'
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/openlibrary-2.1.3/lib/openlibrary/client.rb:1:in `<top (required)>'
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/openlibrary-2.1.3/lib/openlibrary.rb:4:in `require_relative'
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/openlibrary-2.1.3/lib/openlibrary.rb:4:in `<top (required)>'
	from /opt/local/lib/ruby2.1/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /opt/local/lib/ruby2.1/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /opt/local/lib/ruby2.1/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from (irb):1
	from /opt/local/bin/irb:11:in `<main>'
````

**Comment by jedrekdomanski** [comment]
This is not fixed. Just installed it and I am getting the same error message.
