### ISSUE TITLE
Unable to load file

### ISSUE THREAD

**Issue by cincospenguinos** [jayfajardo/openlibrary#25]
I can't require openlibrary:

```
require 'openlibrary'
NameError: uninitialized constant ActiveSupport::Autoload
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/number_helper.rb:3:in `<module:NumberHelper>'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/number_helper.rb:2:in `<module:ActiveSupport>'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/number_helper.rb:1:in `<top (required)>'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:2:in `<top (required)>'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric.rb:3:in `<top (required)>'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext.rb:1:in `each'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext.rb:1:in `<top (required)>'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/openlibrary-2.1.3/lib/openlibrary/request.rb:2:in `<top (required)>'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/openlibrary-2.1.3/lib/openlibrary/client.rb:1:in `require_relative'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/openlibrary-2.1.3/lib/openlibrary/client.rb:1:in `<top (required)>'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/openlibrary-2.1.3/lib/openlibrary.rb:4:in `require_relative'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/openlibrary-2.1.3/lib/openlibrary.rb:4:in `<top (required)>'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from /Users/andre/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from (irb):1
        from /Users/andre/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'
```

Here's my environment:

```
cop-porc024:HomeLibraryManagementService andre$ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.8
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/andre/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/andre/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /Users/andre/.rbenv/versions/2.3.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/andre/.rbenv/versions/2.3.1/bin
  - SPEC CACHE DIRECTORY: /Users/andre/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/andre/.rbenv/versions/2.3.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /Users/andre/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
     - /Users/andre/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/andre/.rbenv/versions/2.3.1/bin
     - /usr/local/Cellar/rbenv/1.0.0/libexec
     - /Users/andre/.rbenv/shims
     - /Users/andre/.rbenv/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/andre/bin
```

**Comment by jedrekdomanski** [comment]
Same thing here. Did you find any solution?

**Comment by flyinggrizzly** [comment]
I think this might be a Ruby version deprecation or something. Try using the version in [PR 32](https://github.com/jayfajardo/openlibrary/pull/32)? 

I'm not getting the error when I use the updated version on Ruby 2.3.x, but I do if I try to require the old version on 2.3.x. 

2 caveats though:

- update requires Rails 5
- currently you'll need to source the gem from Github, not rubygems

**Comment by diek** [comment]
I would love to see this updated.

**Comment by drusepth** [comment]
FWIW, I also get this in Ruby 2.6.x.
