### ISSUE TITLE
Unable to 'require' openlibrary

### ISSUE THREAD

**Issue by jedrekdomanski** [jayfajardo/openlibrary#26]
```2.3.0 :001 > require 'openlibrary'
NameError: uninitialized constant ActiveSupport::Autoload
	from /home/jedrek/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.1/lib/active_support/number_helper.rb:3:in `<module:NumberHelper>'
	from /home/jedrek/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.1/lib/active_support/number_helper.rb:2:in `<module:ActiveSupport>'
	from /home/jedrek/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.1/lib/active_support/number_helper.rb:1:in `<top (required)>'
	from /home/jedrek/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/jedrek/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/jedrek/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.1/lib/active_support/core_ext/numeric/conversions.rb:2:in `<top (required)>'
	from /home/jedrek/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/jedrek/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/jedrek/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.1/lib/active_support/core_ext/numeric.rb:3:in `<top (required)>'
	from /home/jedrek/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /home/jedrek/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /home/jedrek/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.1/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
	from /home/jedrek/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.1/lib/active_support/core_ext.rb:1:in `each'
	from /home/jedrek/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.1/lib/active_support/core_ext.rb:1:in `<top (required)>'
	from /home/jedrek/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/jedrek/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/jedrek/.rvm/gems/ruby-2.3.0/gems/openlibrary-2.1.3/lib/openlibrary/request.rb:2:in `<top (required)>'
	from /home/jedrek/.rvm/gems/ruby-2.3.0/gems/openlibrary-2.1.3/lib/openlibrary/client.rb:1:in `require_relative'
	from /home/jedrek/.rvm/gems/ruby-2.3.0/gems/openlibrary-2.1.3/lib/openlibrary/client.rb:1:in `<top (required)>'
	from /home/jedrek/.rvm/gems/ruby-2.3.0/gems/openlibrary-2.1.3/lib/openlibrary.rb:4:in `require_relative'
	from /home/jedrek/.rvm/gems/ruby-2.3.0/gems/openlibrary-2.1.3/lib/openlibrary.rb:4:in `<top (required)>'
	from /home/jedrek/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /home/jedrek/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /home/jedrek/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from (irb):1
	from /home/jedrek/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'2.3.0 :002 >```

**Comment by jedrekdomanski** [comment]
It looks like it requires `activesupport-4.2.1`. I use `ruby 2.3.0p0` and `activesupport ~> 5.0.2`. I tried cloning the gem and changing to activesupport gem to 5.0.2 in openlibrary.gemspec and it worked fine, however in Rails 5 the bundler won't resolve depndencies for some reason.
